/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Control.ContasPagarDAO;
import Model.ContasPagar;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;





/**
 *
 * @author MARCELO
 */
public class CadastroContasPagar extends javax.swing.JFrame {

    /**
     * Creates new form ContasPagar
     */
    public CadastroContasPagar() {
        initComponents();
       ImageIcon icon = new ImageIcon(getClass().getResource("/Imagens/Emblema_Psicologia.png"));
        setIconImage(icon.getImage());
        DefaultTableModel modelo = (DefaultTableModel) TABContasPagar.getModel();
        TABContasPagar.setRowSorter(new TableRowSorter(modelo));

        readJTable();

            BCadastrar.setEnabled(true);
            BAlterar.setEnabled(false);
            BExcluir.setEnabled(false);
    }

     public void readJTable() {
   
        DefaultTableModel modelo = (DefaultTableModel) TABContasPagar.getModel();
        modelo.setNumRows(0);
        ContasPagarDAO cpdao = new ContasPagarDAO();

        for (ContasPagar cp : cpdao.read()) {

            modelo.addRow(new Object[]{
                cp.getNumero(),
                cp.getDescricao(),
                cp.getData_lancamento(),
                cp.getData_pagamento(),
                cp.getData_vencimento(),
                cp.getValor_a_pagar(),
                cp.getStatus()
            });

        }

    }
    
    public void readJTableForDesc(String desc) {
        
        DefaultTableModel modelo = (DefaultTableModel) TABContasPagar.getModel();
        modelo.setNumRows(0);
        ContasPagarDAO cpdao = new ContasPagarDAO();

        for (ContasPagar cp : cpdao.readForDesc(desc)) {

            
            modelo.addRow(new Object[]{
                cp.getNumero(),
                cp.getDescricao(),
                cp.getData_lancamento(),
                cp.getData_pagamento(),
                cp.getData_vencimento(),
                cp.getValor_a_pagar(),
                cp.getStatus()
            });

        }

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        BCadastrar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TBDescricao = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        TABContasPagar = new javax.swing.JTable();
        TBDataVencimento = new javax.swing.JFormattedTextField();
        TBDataPagamento = new javax.swing.JFormattedTextField();
        TBDataLancamento = new javax.swing.JFormattedTextField();
        BAlterar = new javax.swing.JButton();
        BExcluir = new javax.swing.JButton();
        BBuscar = new javax.swing.JButton();
        TBBuscar = new javax.swing.JTextField();
        CBStatus = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        TBValorPagar = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Contas a Pagar/Pagas");
        setFocusable(false);
        setResizable(false);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        jLabel4.setText("Data de Lançamento");

        jLabel5.setText("Data de Vencimento");

        jLabel2.setText("Descrição");

        jLabel6.setText("Data de Pagamento");

        jLabel7.setText("*Valor a Pagar");

        BCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Cadastrar.png"))); // NOI18N
        BCadastrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BCadastrarMouseClicked(evt);
            }
        });
        BCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCadastrarActionPerformed(evt);
            }
        });

        jLabel8.setText("Status");

        TBDescricao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TBDescricaoKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(TBDescricao);

        TABContasPagar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Número", "Descrição", "Data de Lançamento", "Data de Pagamento", "Data de Vencimento", "Valor a Acertar", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Double.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TABContasPagar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TABContasPagarMouseClicked(evt);
            }
        });
        TABContasPagar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TABContasPagarKeyReleased(evt);
            }
        });
        jScrollPane3.setViewportView(TABContasPagar);

        try {
            TBDataVencimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            TBDataPagamento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            TBDataLancamento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        BAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Alterar.png"))); // NOI18N
        BAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAlterarActionPerformed(evt);
            }
        });

        BExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Excluir.png"))); // NOI18N
        BExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BExcluirActionPerformed(evt);
            }
        });

        BBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Pesquisar2.png"))); // NOI18N
        BBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BBuscarActionPerformed(evt);
            }
        });

        CBStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Pendente", "Paga", " ", " " }));

        jLabel1.setText("Busca por Status");

        TBValorPagar.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat(""))));
        TBValorPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TBValorPagarActionPerformed(evt);
            }
        });

        jLabel3.setText("Campos Obrigatórios *");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(187, 187, 187)
                                        .addComponent(jLabel7)
                                        .addGap(61, 61, 61)
                                        .addComponent(TBValorPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(37, 37, 37)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 617, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel8)
                                        .addGap(39, 39, 39)
                                        .addComponent(CBStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(27, 27, 27)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TBBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(TBDataLancamento, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(67, 67, 67)
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(TBDataVencimento, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(79, 79, 79)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TBDataPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(84, 84, 84))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 1230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addComponent(BCadastrar)
                        .addGap(191, 191, 191)
                        .addComponent(BAlterar)
                        .addGap(198, 198, 198)
                        .addComponent(BExcluir))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(552, 552, 552)
                        .addComponent(jLabel3)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel3)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(106, 106, 106)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(TBValorPagar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(173, 173, 173))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(TBDataLancamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5)
                                    .addComponent(TBDataVencimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6)
                                    .addComponent(TBDataPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(130, 130, 130))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(34, 34, 34)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(CBStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel8))
                                        .addGap(82, 82, 82)
                                        .addComponent(TBBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(BBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)))
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BAlterar)
                    .addComponent(BCadastrar)
                    .addComponent(BExcluir))
                .addGap(52, 52, 52))
        );

        setBounds(0, 0, 1307, 809);
    }// </editor-fold>//GEN-END:initComponents

    private void TABContasPagarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TABContasPagarMouseClicked
  if(TABContasPagar.getSelectedRow() !=-1){
           
            TBDescricao.setText(TABContasPagar.getValueAt(TABContasPagar.getSelectedRow(),1).toString());
            TBDataLancamento.setText(TABContasPagar.getValueAt(TABContasPagar.getSelectedRow(),2).toString());
            TBDataPagamento.setText(TABContasPagar.getValueAt(TABContasPagar.getSelectedRow(),3).toString());
            TBDataVencimento.setText(TABContasPagar.getValueAt(TABContasPagar.getSelectedRow(),4).toString());
            TBValorPagar.setText(TABContasPagar.getValueAt(TABContasPagar.getSelectedRow(),5).toString());            
            CBStatus.setSelectedItem(TABContasPagar.getValueAt(TABContasPagar.getSelectedRow(),6).toString());
            BCadastrar.setEnabled(false);
            BAlterar.setEnabled(true);
            BExcluir.setEnabled(true); 
            
        }
        
    
    }//GEN-LAST:event_TABContasPagarMouseClicked

    private void TABContasPagarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TABContasPagarKeyReleased
        

       if(TABContasPagar.getSelectedRow() !=-1){
           
             TBDescricao.setText(TABContasPagar.getValueAt(TABContasPagar.getSelectedRow(),1).toString());
            TBDataLancamento.setText(TABContasPagar.getValueAt(TABContasPagar.getSelectedRow(),2).toString());
            TBDataPagamento.setText(TABContasPagar.getValueAt(TABContasPagar.getSelectedRow(),3).toString());
            TBDataVencimento.setText(TABContasPagar.getValueAt(TABContasPagar.getSelectedRow(),4).toString());
            TBValorPagar.setText(TABContasPagar.getValueAt(TABContasPagar.getSelectedRow(),5).toString());            
            CBStatus.setSelectedItem(TABContasPagar.getValueAt(TABContasPagar.getSelectedRow(),6).toString());
            BCadastrar.setEnabled(false);
            BAlterar.setEnabled(true);
            BExcluir.setEnabled(true);
        }
        
    }//GEN-LAST:event_TABContasPagarKeyReleased

    private void BCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCadastrarActionPerformed
        
      
        
        if(TBValorPagar.getText().isEmpty()){
        
        JOptionPane.showMessageDialog(null,"preencha o valor a pagar");
           
        }
       
         
        
        else{
              ContasPagar cp = new ContasPagar();
        ContasPagarDAO cpdao = new ContasPagarDAO();
      
        cp.setDescricao(TBDescricao.getText());
        cp.setData_lancamento(TBDataLancamento.getText());
        cp.setData_pagamento(TBDataPagamento.getText());
        cp.setData_vencimento(TBDataVencimento.getText());
        cp.setValor_a_pagar(Double.parseDouble(TBValorPagar.getText()));       
        cp.setStatus(CBStatus.getSelectedItem().toString());
    
 
        cpdao.createContasPagar(cp);
        TBDescricao.setText("");
        TBDataLancamento.setText("");
        TBDataPagamento.setText("");
        TBDataVencimento.setText("");
        TBValorPagar.setText("");
        readJTable();
        }
        
       
         
 
    }//GEN-LAST:event_BCadastrarActionPerformed

    private void BAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAlterarActionPerformed
       if (TABContasPagar.getSelectedRow() != -1) {
         int confirma = JOptionPane.showConfirmDialog(null,"Confirma a alteração desta Conta? ","Atenção",JOptionPane.YES_NO_OPTION);
        if (confirma== JOptionPane.YES_OPTION){
            if(TBValorPagar.getText().isEmpty()){
        
        JOptionPane.showMessageDialog(null,"preencha o valor a pagar");
        
        }
       
       
        else{
           
           ContasPagar cp = new   ContasPagar();
        ContasPagarDAO cpdao = new ContasPagarDAO();

        
        cp.setDescricao(TBDescricao.getText());
        cp.setData_lancamento(TBDataLancamento.getText());
       
        cp.setData_pagamento(TBDataPagamento.getText());
        cp.setData_vencimento(TBDataVencimento.getText());
        cp.setValor_a_pagar(Double.parseDouble(TBValorPagar.getText()));      
        cp.setStatus(CBStatus.getSelectedItem().toString());
        cp.setNumero((int) TABContasPagar.getValueAt(TABContasPagar.getSelectedRow(), 0));
        cpdao.update(cp);

        TBDataPagamento.setText("");
        TBDescricao.setText("");
        TBValorPagar.setText("");
        TBDataVencimento.setText("");
        TBDataLancamento.setText("");
        
        

            readJTable();

        }
          
        }
        else{
        
        }
       }
       else{
       
       JOptionPane.showMessageDialog(null,"Selecione uma Conta para alterar");
           
       }
    }//GEN-LAST:event_BAlterarActionPerformed

    private void BExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BExcluirActionPerformed
        if (TABContasPagar.getSelectedRow() != -1) {
 int confirma = JOptionPane.showConfirmDialog(null,"Confirma a exclusão desta Conta? ","Atenção",JOptionPane.YES_NO_OPTION);
        if (confirma== JOptionPane.YES_OPTION){
            ContasPagar cp = new ContasPagar();
            ContasPagarDAO cpdao = new ContasPagarDAO();

            cp.setNumero((int) TABContasPagar.getValueAt(TABContasPagar.getSelectedRow(), 0));
            
            cpdao.delete(cp);
        TBDataPagamento.setText("");
        TBDescricao.setText("");
        TBValorPagar.setText("");
        TBDataVencimento.setText("");
        TBDataLancamento.setText("");
        
        

          

            readJTable();

        } 
        else{
        
        }
        }
        else {
            JOptionPane.showMessageDialog(null, "Selecione uma Conta para excluir.");
        }
       
    }//GEN-LAST:event_BExcluirActionPerformed

    private void BBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BBuscarActionPerformed
        readJTableForDesc(TBBuscar.getText());
    }//GEN-LAST:event_BBuscarActionPerformed

    private void TBValorPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TBValorPagarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TBValorPagarActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
      
    }//GEN-LAST:event_formMouseClicked

    private void BCadastrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BCadastrarMouseClicked
        TBDataPagamento.setText("");
        TBDescricao.setText("");
        TBValorPagar.setText("");
        TBDataVencimento.setText("");
        TBDataLancamento.setText("");
        
        BCadastrar.setEnabled(true);
        BAlterar.setEnabled(false);
        BExcluir.setEnabled(false);    }//GEN-LAST:event_BCadastrarMouseClicked

    private void TBDescricaoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TBDescricaoKeyTyped
       if (TBDescricao.getText().length() >= 956){
       
           evt.consume();
       
       }
    }//GEN-LAST:event_TBDescricaoKeyTyped

    /**
     * 
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroContasPagar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroContasPagar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroContasPagar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroContasPagar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
              
                new CadastroContasPagar().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BAlterar;
    private javax.swing.JButton BBuscar;
    private javax.swing.JButton BCadastrar;
    private javax.swing.JButton BExcluir;
    private javax.swing.JComboBox<String> CBStatus;
    private javax.swing.JTable TABContasPagar;
    private javax.swing.JTextField TBBuscar;
    private javax.swing.JFormattedTextField TBDataLancamento;
    private javax.swing.JFormattedTextField TBDataPagamento;
    private javax.swing.JFormattedTextField TBDataVencimento;
    private javax.swing.JTextPane TBDescricao;
    private javax.swing.JFormattedTextField TBValorPagar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables

    
}
