/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Control.Conexao;
import Control.PacienteDAO;
import Control.PsicologoDAO;
import Model.Paciente;
import Model.Psicologo;
import java.util.HashMap;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author MARCELO
 */
public class RelatorioPacientes extends javax.swing.JFrame {

    /**
     * Creates new form ExibicaoPacientes
     */
    public RelatorioPacientes() {
        initComponents();
        
         ImageIcon icon = new ImageIcon(getClass().getResource("/Imagens/Emblema_Psicologia.png"));
        setIconImage(icon.getImage());
        
    }
public void readJTable() {
   
        DefaultTableModel modelo = (DefaultTableModel) TABPacientes.getModel();
        modelo.setNumRows(0);
        PacienteDAO pdao = new PacienteDAO();

        for (Paciente p : pdao.read()) {

            modelo.addRow(new Object[]{
                p.getCpf(),
                p.getNome(),
                p.getEmail(),
                p.getTelefone(),
                p.getSexo(),
                p.getEstado_civil(),
                p.getData_nascimento(),
                 
               
            });

        }
  }
         public void readJTable1() {
   
        DefaultTableModel modelo = (DefaultTableModel) TABEnderecoPaciente.getModel();
        modelo.setNumRows(0);
        PacienteDAO pdao = new PacienteDAO();

        for (Paciente p : pdao.read()) {

            modelo.addRow(new Object[]{
          
                p.getNumero_endereco(),
                p.getCep(),
                p.getRua(),
                p.getEstado(),
                p.getBairro(),
                p.getCidade()    
               
            });

        }
        

    }
         
           private void emitirRelatorioPaciente(){
    
            int confirma = JOptionPane.showConfirmDialog(null,"Confirma a emissão deste Relatório? ","Atenção",JOptionPane.YES_NO_OPTION);
      if(confirma== JOptionPane.YES_OPTION){
          try{
               if(TBEmitir.getText().isEmpty()){
                  
                  JOptionPane.showMessageDialog(null," Insira um CPF de um Paciente para a emissão do Relatório");
                  
              }
               else{
              HashMap filtro = new HashMap();
              filtro.put("cpf",TBEmitir.getText());
              JasperPrint print =JasperFillManager.fillReport("C://Users//MARCELO//Documents////AMAConsult//relatórios//Pacientes/Pacientes.jasper",filtro,Conexao.getConnection());
              TBEmitir.setText("");
              JasperViewer.viewReport(print,false);
             
               }
          }catch(Exception e){
              
              JOptionPane.showMessageDialog(null,"Insira um CPF válido!");
               TBEmitir.setText("");
          }
          
      }
      else{
          
           TBEmitir.setText("");
          
      }
    
}
         
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TABPacientes = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        TABEnderecoPaciente = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        BEmitir = new javax.swing.JButton();
        TBEmitir = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Relatório de Pacientes");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        TABPacientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "CPF", "Nome", "Email", "Telefone", "Sexo", "Estado civil", "Data de Nascimento"
            }
        ));
        TABPacientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TABPacientesMouseClicked(evt);
            }
        });
        TABPacientes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TABPacientesKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(TABPacientes);

        TABEnderecoPaciente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Número da Residência", "CEP", "Rua", "Estado", "Bairro", "Cidade"
            }
        ));
        TABEnderecoPaciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TABEnderecoPacienteMouseClicked(evt);
            }
        });
        TABEnderecoPaciente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TABEnderecoPacienteKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(TABEnderecoPaciente);

        jLabel1.setText("Dados dos Pacientes");

        BEmitir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Imprimirv2.jpg"))); // NOI18N
        BEmitir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BEmitirActionPerformed(evt);
            }
        });

        TBEmitir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TBEmitirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(315, Short.MAX_VALUE)
                .addComponent(TBEmitir, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(BEmitir, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(507, 507, 507))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(515, 515, 515)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabel1)
                .addGap(60, 60, 60)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(TBEmitir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(BEmitir, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(104, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TABEnderecoPacienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TABEnderecoPacienteMouseClicked
       
      
        if (TABPacientes.getSelectedRow() != -1) {
            TBEmitir.setText(TABPacientes.getValueAt(TABPacientes.getSelectedRow(),0).toString());
        }
    }//GEN-LAST:event_TABEnderecoPacienteMouseClicked

    private void TABEnderecoPacienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TABEnderecoPacienteKeyReleased
         if (TABPacientes.getSelectedRow() != -1) {
            TBEmitir.setText(TABPacientes.getValueAt(TABPacientes.getSelectedRow(),0).toString());
        }
    }//GEN-LAST:event_TABEnderecoPacienteKeyReleased

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
          readJTable();
        readJTable1();
    }//GEN-LAST:event_formWindowActivated

    private void BEmitirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BEmitirActionPerformed
        emitirRelatorioPaciente();
    }//GEN-LAST:event_BEmitirActionPerformed

    private void TBEmitirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TBEmitirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TBEmitirActionPerformed

    private void TABPacientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TABPacientesMouseClicked
        if (TABPacientes.getSelectedRow() != -1) {
            TBEmitir.setText(TABPacientes.getValueAt(TABPacientes.getSelectedRow(),0).toString());
        }
    }//GEN-LAST:event_TABPacientesMouseClicked

    private void TABPacientesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TABPacientesKeyReleased
      if (TABPacientes.getSelectedRow() != -1) {
            TBEmitir.setText(TABPacientes.getValueAt(TABPacientes.getSelectedRow(),0).toString());
        }
    }//GEN-LAST:event_TABPacientesKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RelatorioPacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RelatorioPacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RelatorioPacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RelatorioPacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RelatorioPacientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BEmitir;
    private javax.swing.JTable TABEnderecoPaciente;
    private javax.swing.JTable TABPacientes;
    private javax.swing.JTextField TBEmitir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
