/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Control.Conexao;
import Control.PsicologoDAO;
import Model.Psicologo;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
import java.sql.*;
import javax.swing.ImageIcon;
/**
 *
 * @author MARCELO
 */
public class RelatorioPsicologos extends javax.swing.JFrame {

    /**
     * Creates new form ExibicaoPsicologos
     */
    public RelatorioPsicologos() {
        initComponents();
        
     ImageIcon icon = new ImageIcon(getClass().getResource("/Imagens/Emblema_Psicologia.png"));
        setIconImage(icon.getImage());
        
    }
  public void readJTable() {
   
        DefaultTableModel modelo = (DefaultTableModel) TABPsicologos.getModel();
        modelo.setNumRows(0);
        PsicologoDAO pdao = new PsicologoDAO();

        for (Psicologo p : pdao.read()) {

            modelo.addRow(new Object[]{
                p.getCpf(),
                p.getNome(),
                p.getEmail(),
                p.getTelefone(),
                p.getSexo(),
                p.getEstado_civil(),
                p.getData_nascimento(),
                 
               
            });

        }
  }
         public void readJTable1() {
   
        DefaultTableModel modelo = (DefaultTableModel) TABEndereco.getModel();
        modelo.setNumRows(0);
        PsicologoDAO pdao = new PsicologoDAO();

        for (Psicologo p : pdao.read()) {

            modelo.addRow(new Object[]{
          
                p.getNumero_endereco(),
                p.getCep(),
                p.getRua(),
                p.getEstado(),
                p.getBairro(),
                p.getCidade()    
               
            });

        }
        

    }
         
         private void emitirRelatorioPsicologo(){
    
            int confirma = JOptionPane.showConfirmDialog(null,"Confirma a emissão deste Relatório? ","Atenção",JOptionPane.YES_NO_OPTION);
      if(confirma== JOptionPane.YES_OPTION){
          try{
               if(TBEmitir.getText().isEmpty()){
                  
                  JOptionPane.showMessageDialog(null," Insira um CPF de um Psicólogo para a emissão do Relatório");
                  
              }
               else{
              HashMap filtro = new HashMap();
              filtro.put("cpf",TBEmitir.getText());
              JasperPrint print =JasperFillManager.fillReport("C://Users//MARCELO//Documents//AMAConsult//relatórios//Psicólogos/Psicólogos.jasper",filtro,Conexao.getConnection());
              TBEmitir.setText("");
              JasperViewer.viewReport(print,false);
             
               }
          }catch(Exception e){
              
              JOptionPane.showMessageDialog(null,"");
              
          }
          
      }
      else{
          
          TBEmitir.setText("");
          
      }
    
}

         
         
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TABEndereco = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        TABPsicologos = new javax.swing.JTable();
        BEmitir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        TBEmitir = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Relatório de Psicólogos");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        TABEndereco.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Número da Residência", "CEP", "Rua", "Estado", "Bairro", "Cidade"
            }
        ));
        TABEndereco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TABEnderecoMouseClicked(evt);
            }
        });
        TABEndereco.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TABEnderecoKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(TABEndereco);

        TABPsicologos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "CPF", "Nome", "Email", "Telefone", "Sexo", "Estado civil", "Data de Nascimento"
            }
        ));
        TABPsicologos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TABPsicologosMouseClicked(evt);
            }
        });
        TABPsicologos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TABPsicologosKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(TABPsicologos);

        BEmitir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Imprimirv2.jpg"))); // NOI18N
        BEmitir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BEmitirActionPerformed(evt);
            }
        });

        jLabel1.setText("Dados dos Psicólogos");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TBEmitir, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BEmitir, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(552, 552, 552))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(606, 606, 606)
                .addComponent(jLabel1)
                .addContainerGap(711, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(TBEmitir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(BEmitir, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(2271, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setBounds(0, 0, 1492, 793);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
      
        readJTable();
        readJTable1();
    }//GEN-LAST:event_formWindowActivated

    private void TABEnderecoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TABEnderecoKeyReleased
        
        if (TABPsicologos.getSelectedRow() != -1) {
            TBEmitir.setText(TABPsicologos.getValueAt(TABPsicologos.getSelectedRow(),0).toString());
            
        }
        
    }//GEN-LAST:event_TABEnderecoKeyReleased

    private void TABEnderecoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TABEnderecoMouseClicked
         if (TABPsicologos.getSelectedRow() != -1) {
            TBEmitir.setText(TABPsicologos.getValueAt(TABPsicologos.getSelectedRow(),0).toString());
            
        }
    }//GEN-LAST:event_TABEnderecoMouseClicked

    private void BEmitirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BEmitirActionPerformed
        emitirRelatorioPsicologo();
    }//GEN-LAST:event_BEmitirActionPerformed

    private void TABPsicologosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TABPsicologosKeyReleased
          if (TABPsicologos.getSelectedRow() != -1) {
            TBEmitir.setText(TABPsicologos.getValueAt(TABPsicologos.getSelectedRow(),0).toString());
            
        }
    }//GEN-LAST:event_TABPsicologosKeyReleased

    private void TABPsicologosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TABPsicologosMouseClicked
         if (TABPsicologos.getSelectedRow() != -1) {
            TBEmitir.setText(TABPsicologos.getValueAt(TABPsicologos.getSelectedRow(),0).toString());
            
        }
    }//GEN-LAST:event_TABPsicologosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RelatorioPsicologos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RelatorioPsicologos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RelatorioPsicologos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RelatorioPsicologos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RelatorioPsicologos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BEmitir;
    private javax.swing.JTable TABEndereco;
    private javax.swing.JTable TABPsicologos;
    private javax.swing.JTextField TBEmitir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
