/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Control.Conexao;
import Control.ContasPagarDAO;
import Model.ContasPagar;
import java.util.HashMap;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author MARCELO
 */
public class RelatorioContasPagar extends javax.swing.JFrame {

    /**
     * Creates new form ExibiçãoContasPagar
     */
    public RelatorioContasPagar() {
        initComponents();
       ImageIcon icon = new ImageIcon(getClass().getResource("/Imagens/Emblema_Psicologia.png"));
        setIconImage(icon.getImage());  
       
    }
   
public void readJTable() {
  
        DefaultTableModel modelo = (DefaultTableModel) TABContasPagar.getModel();
        modelo.setNumRows(0);
        ContasPagarDAO cpdao = new ContasPagarDAO();

        for (ContasPagar cp : cpdao.read()) {

            modelo.addRow(new Object[]{
                cp.getNumero(),
                cp.getDescricao(),
                cp.getData_lancamento(),
                cp.getData_pagamento(),
                cp.getData_vencimento(),
                cp.getValor_a_pagar(),
                cp.getStatus()
            });

        }

    }
public void readJTableForDesc(String desc) {
        
        DefaultTableModel modelo = (DefaultTableModel) TABContasPagar.getModel();
        modelo.setNumRows(0);
        ContasPagarDAO cpdao = new ContasPagarDAO();

        for (ContasPagar cp : cpdao.readForDesc(desc)) {

            modelo.addRow(new Object[]{
                cp.getNumero(),
                cp.getDescricao(),
                cp.getData_lancamento(),
                cp.getData_pagamento(),
                cp.getData_vencimento(),
                cp.getValor_a_pagar(),
                cp.getStatus()
            });

        }
}

   private void emitirRelatorioContasPagar(){
    
            int confirma = JOptionPane.showConfirmDialog(null,"Confirma a emissão deste Relatório? ","Atenção",JOptionPane.YES_NO_OPTION);
      if(confirma== JOptionPane.YES_OPTION){
          try{
               if(TBEmitir.getText().isEmpty()){
                  
                  JOptionPane.showMessageDialog(null," Insira o número da conta a pagar do consultório para a emissão do Relatório ");
                  
              }
               else{
              HashMap filtro = new HashMap();
              filtro.put("numero",Integer.parseInt(TBEmitir.getText()));
              JasperPrint print =JasperFillManager.fillReport("C://Users//MARCELO//Documents//AMAConsult//relatórios//Contas a Pagar ou Pagas/Contas a Pagar ou Pagas.jasper",filtro,Conexao.getConnection());
              TBEmitir.setText("");
              JasperViewer.viewReport(print,false);
             
               }
          }catch(Exception e){
              
              JOptionPane.showMessageDialog(null,"Digite um número válido ");
                TBEmitir.setText("");
          }
          
      }
      else{
          
            TBEmitir.setText("");
          
      }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        TABContasPagar = new javax.swing.JTable();
        BEmitir = new javax.swing.JButton();
        TBEmitir = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Relatório de Contas a Pagar/Pagas");
        setFocusable(false);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        TABContasPagar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Número", "Descrição", "Data de Lançamento", "Data de Pagamento", "Data de Vencimento", "Valor a Acertar", "Status"
            }
        ));
        TABContasPagar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TABContasPagarMouseClicked(evt);
            }
        });
        TABContasPagar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TABContasPagarKeyReleased(evt);
            }
        });
        jScrollPane3.setViewportView(TABContasPagar);

        BEmitir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Imprimirv2.jpg"))); // NOI18N
        BEmitir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BEmitirActionPerformed(evt);
            }
        });

        TBEmitir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TBEmitirActionPerformed(evt);
            }
        });

        jLabel1.setText("Dados de Contas a Pagar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(632, 632, 632)
                .addComponent(jLabel1)
                .addContainerGap(668, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TBEmitir, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(BEmitir, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(568, 568, 568))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(TBEmitir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(BEmitir, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(199, Short.MAX_VALUE))
        );

        setBounds(0, 0, 1499, 773);
    }// </editor-fold>//GEN-END:initComponents

    private void TABContasPagarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TABContasPagarKeyReleased
    if(TABContasPagar.getSelectedRow() !=-1){
            TBEmitir.setText(TABContasPagar.getValueAt(TABContasPagar.getSelectedRow(),0).toString());
          
        }    
          
    }//GEN-LAST:event_TABContasPagarKeyReleased

    private void TABContasPagarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TABContasPagarMouseClicked
       if(TABContasPagar.getSelectedRow() !=-1){
            TBEmitir.setText(TABContasPagar.getValueAt(TABContasPagar.getSelectedRow(),0).toString());
          
        }  
        
        
    }//GEN-LAST:event_TABContasPagarMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
       readJTable();
    }//GEN-LAST:event_formWindowActivated

    private void BEmitirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BEmitirActionPerformed
        emitirRelatorioContasPagar();
    }//GEN-LAST:event_BEmitirActionPerformed

    private void TBEmitirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TBEmitirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TBEmitirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RelatorioContasPagar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RelatorioContasPagar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RelatorioContasPagar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RelatorioContasPagar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RelatorioContasPagar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BEmitir;
    private javax.swing.JTable TABContasPagar;
    private javax.swing.JTextField TBEmitir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
