/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Control.ConsultaDAO;
import Control.ContasReceberDAO;
import Control.PacienteDAO;
import Control.PsicologoDAO;
import Model.Consulta;
import Model.ContasReceber;
import Model.Paciente;
import Model.Psicologo;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;


/**
 *
 * @author MARCELO
 */
public class TelaContasReceber extends javax.swing.JFrame {
Connection conexao = null;
PreparedStatement stmt  = null;
ResultSet rs = null;
    /**
     * Creates new form CadastroContasReceber
     */
    public TelaContasReceber() {
        initComponents();
         ImageIcon icon = new ImageIcon(getClass().getResource("/Imagens/Emblema_Psicologia.png"));
        setIconImage(icon.getImage());
          DefaultTableModel modelo = (DefaultTableModel) TABContasReceber.getModel();
          TABContasReceber.setRowSorter(new TableRowSorter(modelo));

        readJTable(); 
           DefaultTableModel modelo1 = (DefaultTableModel) TABNumero.getModel();
            TABNumero.setRowSorter(new TableRowSorter(modelo1));
            pesquisarNumeroConsulta();
                 BCadastrar.setEnabled(true);
                 BAlterar.setEnabled(false);
                 BExcluir.setEnabled(false);
    }
 public void readJTable() {
   
        DefaultTableModel modelo = (DefaultTableModel) TABContasReceber.getModel();
        modelo.setNumRows(0);
       
        Consulta consulta = new Consulta();
     
        ContasReceberDAO rcdao = new ContasReceberDAO();
        for (ContasReceber cr : rcdao.read()) {

            modelo.addRow(new Object[]{
                
                cr.getConsulta().getNumero(),
                 cr.getValor_a_receber(),
                cr.getData_lancamento(),
                cr.getData_recebimento(),
                cr.getTipo(),
                cr.getStatus(), 
               
            });

        }

    }
 

    
 
  public void readJTableForDesc(String desc) {
        
        DefaultTableModel modelo = (DefaultTableModel) TABContasReceber.getModel();
        modelo.setNumRows(0);
        ContasReceberDAO crdao = new ContasReceberDAO();

        for (ContasReceber cr : crdao.readForDesc(desc)) {

            
            modelo.addRow(new Object[]{
                cr.getConsulta().getNumero(),
                cr.getValor_a_receber(),
                cr.getData_lancamento(),
                cr.getData_recebimento(),
                cr.getTipo(),
                cr.getStatus() 
            });

        }

    }
  public void pesquisarNumeroConsulta() {
   
        DefaultTableModel modelo = (DefaultTableModel) TABNumero.getModel();
        modelo.setNumRows(0);
       
        ConsultaDAO cdao = new ConsultaDAO();
       
        for (Consulta c : cdao.pesquisarNumeroConsulta()) {

            modelo.addRow(new Object[]{
                c.getNumero()
            });

        }
       

  }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BCadastrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TABContasReceber = new javax.swing.JTable();
        BAlterar = new javax.swing.JButton();
        BExcluir = new javax.swing.JButton();
        BBuscar = new javax.swing.JButton();
        TBBuscar = new javax.swing.JTextField();
        CBTipoPagamento = new javax.swing.JComboBox<>();
        CBStatus = new javax.swing.JComboBox<>();
        TBDataLancamento = new javax.swing.JFormattedTextField();
        TBDataRecebimento = new javax.swing.JFormattedTextField();
        TBValorReceber = new javax.swing.JFormattedTextField();
        TBNumero = new javax.swing.JFormattedTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        TABNumero = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consultas a Receber");
        setResizable(false);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        BCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Cadastrar.png"))); // NOI18N
        BCadastrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BCadastrarMouseClicked(evt);
            }
        });
        BCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCadastrarActionPerformed(evt);
            }
        });

        jLabel1.setText("*Nº Consulta");

        jLabel2.setText("Data de Lançamento");

        jLabel3.setText("Data de Recebimento");

        jLabel4.setText("Forma de Pagamento");

        jLabel5.setText("*Valor a Receber");

        jLabel6.setText("Status");

        TABContasReceber.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nº Consulta", "Valor a Receber", "Data de Lançamento", "Data de Recebimento", "Forma de Pagamento", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TABContasReceber.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TABContasReceberMouseClicked(evt);
            }
        });
        TABContasReceber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TABContasReceberKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TABContasReceberKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(TABContasReceber);

        BAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Alterar.png"))); // NOI18N
        BAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAlterarActionPerformed(evt);
            }
        });

        BExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Excluir.png"))); // NOI18N
        BExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BExcluirActionPerformed(evt);
            }
        });

        BBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Pesquisar2.png"))); // NOI18N
        BBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BBuscarActionPerformed(evt);
            }
        });

        CBTipoPagamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Dinheiro\t", "Cartão", "Convênio" }));

        CBStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pendente\t", "Paga" }));
        CBStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBStatusActionPerformed(evt);
            }
        });

        try {
            TBDataLancamento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            TBDataRecebimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        TBValorReceber.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat(""))));

        TBNumero.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("0"))));

        TABNumero.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Nº da Consulta"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TABNumero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TABNumeroMouseClicked(evt);
            }
        });
        TABNumero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TABNumeroKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(TABNumero);

        jLabel7.setText("Busca por número de consulta");

        jLabel8.setText("Campos Obrigatórios *");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TBNumero, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                            .addComponent(jLabel1)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(272, 272, 272)
                                .addComponent(jLabel8))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(TBDataLancamento, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(CBTipoPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(18, 18, 18)
                                        .addComponent(TBValorReceber, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)
                                        .addComponent(TBDataRecebimento, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel6)
                                                .addGap(18, 18, 18)
                                                .addComponent(CBStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabel7)
                                            .addComponent(TBBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addComponent(BBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(BCadastrar)
                        .addGap(136, 136, 136)
                        .addComponent(BAlterar)
                        .addGap(140, 140, 140)
                        .addComponent(BExcluir)))
                .addContainerGap(96, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(93, 93, 93))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(101, 101, 101)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel4)
                                            .addComponent(CBTipoPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel6)
                                            .addComponent(CBStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(jLabel1)
                                        .addGap(37, 37, 37)
                                        .addComponent(TBNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(TBBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5)
                                    .addComponent(TBValorReceber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7)
                                .addGap(85, 85, 85))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(TBDataLancamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)
                                    .addComponent(TBDataRecebimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(65, 65, 65)
                                .addComponent(BBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BAlterar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BExcluir, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BCadastrar)))
                .addGap(34, 34, 34))
        );

        setBounds(0, 0, 1159, 789);
    }// </editor-fold>//GEN-END:initComponents

    private void BCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCadastrarActionPerformed
    
        if(TBNumero.getText().isEmpty()||TBValorReceber.getText().isEmpty()){
               
               JOptionPane.showMessageDialog(null,"Preencha todos os campos obrigatórios"); 
               
              
               
              } 
      else{
        Consulta consulta = new Consulta();
    ConsultaDAO cdao = new ConsultaDAO();
    ContasReceber cr = new ContasReceber();
    ContasReceberDAO crdao = new ContasReceberDAO();
    cr.setConsulta(consulta);
    consulta.setNumero(Integer.parseInt(TBNumero.getText()));
    cr.setData_lancamento(TBDataLancamento.getText());
    cr.setData_recebimento(TBDataRecebimento.getText());
    cr.setValor_a_receber(Double.parseDouble(TBValorReceber.getText()));
    cr.setTipo(CBTipoPagamento.getSelectedItem().toString());
    cr.setStatus(CBStatus.getSelectedItem().toString());
    crdao.createContasReceber(cr);  
    TBNumero.setText("");
    TBDataLancamento.setText("");
    TBDataRecebimento.setText("");
    TBValorReceber.setText("");
    
     
      readJTable();
      }
     
    }//GEN-LAST:event_BCadastrarActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
     readJTable();
    }//GEN-LAST:event_formWindowActivated

    private void BAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAlterarActionPerformed
           
        if (TABContasReceber.getSelectedRow() != - 1) { 
       int confirma = JOptionPane.showConfirmDialog(null,"Confirma a alteração desta Conta? ","Atenção",JOptionPane.YES_NO_OPTION);
        if (confirma== JOptionPane.YES_OPTION){
          if(TBNumero.getText().isEmpty()||TBValorReceber.getText().isEmpty()){
               
               JOptionPane.showMessageDialog(null,"Preencha todos os campos obrigatórios"); 
              }          
          else{
          ContasReceber cr = new ContasReceber();
         ContasReceberDAO crdao= new ContasReceberDAO();
         Consulta consulta = new Consulta();
       
          cr.setData_lancamento(TBDataLancamento.getText());
          cr.setData_recebimento(TBDataRecebimento.getText());
          cr.setValor_a_receber(Double.parseDouble(TBValorReceber.getText()));
          cr.setTipo(CBTipoPagamento.getSelectedItem().toString());
          cr.setStatus(CBStatus.getSelectedItem().toString());
         consulta.setNumero((int)TABContasReceber.getValueAt(TABContasReceber.getSelectedRow(), 0));
              cr.setConsulta(consulta);
        crdao.update(cr);
            TBNumero.setText("");
            TBDataLancamento.setText("");
            TBDataRecebimento.setText("");
            TBValorReceber.setText("");
        readJTable();
            
            

        }
              }
        
        else{}
        
        
        }
         else {
            JOptionPane.showMessageDialog(null, "Selecione uma Conta para alterar");
        
        }
       
    }//GEN-LAST:event_BAlterarActionPerformed

    private void BExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BExcluirActionPerformed
       if (TABContasReceber.getSelectedRow() != -1) {
            int confirma = JOptionPane.showConfirmDialog(null,"Confirma a exclusão desta Conta? ","Atenção",JOptionPane.YES_NO_OPTION);
        if (confirma== JOptionPane.YES_OPTION){
        Consulta c = new Consulta();
        ContasReceber cr = new  ContasReceber();
          ContasReceberDAO crdao = new  ContasReceberDAO();

            c.setNumero((int) TABContasReceber.getValueAt(TABContasReceber.getSelectedRow(), 0));
            cr.setConsulta(c);
            crdao.delete(cr);
                 TBNumero.setText("");
                 TBDataLancamento.setText("");
                 TBDataRecebimento.setText("");
                 TBValorReceber.setText("");
          

            readJTable();

        }
        else{}
       }
        else {
            JOptionPane.showMessageDialog(null, "Selecione uma Conta para excluir.");
        }
       
    }//GEN-LAST:event_BExcluirActionPerformed

    private void BBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BBuscarActionPerformed
   readJTableForDesc(TBBuscar.getText());
    }//GEN-LAST:event_BBuscarActionPerformed

    private void CBStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBStatusActionPerformed

    private void TABContasReceberKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TABContasReceberKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_TABContasReceberKeyPressed

    private void TABContasReceberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TABContasReceberKeyReleased
        
        if(TABContasReceber.getSelectedRow() !=-1){
            TBNumero.setText(TABContasReceber.getValueAt(TABContasReceber.getSelectedRow(),0).toString());
            TBValorReceber.setText(TABContasReceber.getValueAt(TABContasReceber.getSelectedRow(),1).toString());
            TBDataLancamento.setText(TABContasReceber.getValueAt(TABContasReceber.getSelectedRow(),2).toString());
            TBDataRecebimento.setText(TABContasReceber.getValueAt(TABContasReceber.getSelectedRow(),3).toString());
            CBTipoPagamento.setSelectedItem((TABContasReceber.getValueAt(TABContasReceber.getSelectedRow(),4).toString()));
            CBStatus.setSelectedItem(TABContasReceber.getValueAt(TABContasReceber.getSelectedRow(),5).toString());
            BCadastrar.setEnabled(false);
            BAlterar.setEnabled(true);
            BExcluir.setEnabled(true);
        }
        
    }//GEN-LAST:event_TABContasReceberKeyReleased

    private void TABContasReceberMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TABContasReceberMouseClicked
         
        if(TABContasReceber.getSelectedRow() !=-1){
            TBNumero.setText(TABContasReceber.getValueAt(TABContasReceber.getSelectedRow(),0).toString());
            TBValorReceber.setText(TABContasReceber.getValueAt(TABContasReceber.getSelectedRow(),1).toString());
            TBDataLancamento.setText(TABContasReceber.getValueAt(TABContasReceber.getSelectedRow(),2).toString());
            TBDataRecebimento.setText(TABContasReceber.getValueAt(TABContasReceber.getSelectedRow(),3).toString());
            CBTipoPagamento.setSelectedItem((TABContasReceber.getValueAt(TABContasReceber.getSelectedRow(),4).toString()));
            CBStatus.setSelectedItem(TABContasReceber.getValueAt(TABContasReceber.getSelectedRow(),5).toString());
            BCadastrar.setEnabled(false);
            BAlterar.setEnabled(true);
            BExcluir.setEnabled(true);
        }
        
    }//GEN-LAST:event_TABContasReceberMouseClicked

    private void TABNumeroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TABNumeroKeyReleased
             TBNumero.setText(TABNumero.getValueAt(TABNumero.getSelectedRow(),0).toString());
    }//GEN-LAST:event_TABNumeroKeyReleased

    private void TABNumeroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TABNumeroMouseClicked
      TBNumero.setText(TABNumero.getValueAt(TABNumero.getSelectedRow(),0).toString());


    
    }//GEN-LAST:event_TABNumeroMouseClicked

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
         
          
    }//GEN-LAST:event_formMouseClicked

    private void BCadastrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BCadastrarMouseClicked
                 TBNumero.setText("");
                 TBDataLancamento.setText("");
                 TBDataRecebimento.setText("");
                 TBValorReceber.setText("");
                 BCadastrar.setEnabled(true);
                 BAlterar.setEnabled(false);
                 BExcluir.setEnabled(false);
    }//GEN-LAST:event_BCadastrarMouseClicked

   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaContasReceber.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaContasReceber.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaContasReceber.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaContasReceber.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaContasReceber().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BAlterar;
    private javax.swing.JButton BBuscar;
    private javax.swing.JButton BCadastrar;
    private javax.swing.JButton BExcluir;
    private javax.swing.JComboBox<String> CBStatus;
    private javax.swing.JComboBox<String> CBTipoPagamento;
    private javax.swing.JTable TABContasReceber;
    private javax.swing.JTable TABNumero;
    private javax.swing.JTextField TBBuscar;
    private javax.swing.JFormattedTextField TBDataLancamento;
    private javax.swing.JFormattedTextField TBDataRecebimento;
    private javax.swing.JFormattedTextField TBNumero;
    private javax.swing.JFormattedTextField TBValorReceber;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
