/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;


import Control.ConsultaDAO;
import Control.ContasPagarDAO;
import Control.PsicologoDAO;
import Model.Consulta;
import Model.ContasPagar;

import Model.Psicologo;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author MARCELO
 */
public class TelaCadastroPsicologo extends javax.swing.JFrame {

    /**
     * Creates new form TelaPsicologo
     */
    public TelaCadastroPsicologo() {
        initComponents();   
        ImageIcon icon = new ImageIcon(getClass().getResource("/Imagens/Emblema_Psicologia.png"));
        setIconImage(icon.getImage());
         DefaultTableModel modelo = (DefaultTableModel) TABPsicologos.getModel();
        TABPsicologos.setRowSorter(new TableRowSorter(modelo));

        readJTable();
        
            BCadastrar.setEnabled(true);
            BAlterar.setEnabled(false);
            BExcluir.setEnabled(false);
        
    }

    /**
     *
     */
    public void readJTable() {
   
        DefaultTableModel modelo = (DefaultTableModel) TABPsicologos.getModel();
        modelo.setNumRows(0);
        PsicologoDAO pdao = new PsicologoDAO();

        for (Psicologo p : pdao.read()) {

            modelo.addRow(new Object[]{
                p.getCpf(),
                p.getNome(),
                p.getEmail(),
                p.getTelefone(),
                p.getSexo(),
                p.getEstado_civil(),
                p.getData_nascimento(),
                p.getNumero_endereco(),
                p.getCep(),
                p.getRua(),
                p.getBairro(),
                p.getCidade(),
                p.getEstado() 
               
            });

        }

    }
     
    /**
     *
     * @param desc
     */
    public void readJTableForDesc(String desc) {
        
        DefaultTableModel modelo = (DefaultTableModel) TABPsicologos.getModel();
        modelo.setNumRows(0);
        PsicologoDAO pdao = new PsicologoDAO();

        for (Psicologo p : pdao.readForDesc(desc)) {

            
            modelo.addRow(new Object[]{
                p.getCpf(),
                p.getNome(),
                p.getEmail(),
                p.getTelefone(),
                p.getSexo(),
                p.getEstado_civil(),
                p.getData_nascimento(),
                p.getNumero_endereco(),
                p.getCep(),
                p.getRua(),
                p.getBairro(),
                p.getCidade(),
                p.getEstado()                    
            });

        }

    }
 
  
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        TBBairro = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        BCadastrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TABPsicologos = new javax.swing.JTable();
        BAlterar = new javax.swing.JButton();
        BExcluir = new javax.swing.JButton();
        BBuscar = new javax.swing.JButton();
        TBBuscar = new javax.swing.JTextField();
        CBSexo = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        TBCPF = new javax.swing.JFormattedTextField();
        TBTelefone = new javax.swing.JFormattedTextField();
        TBDataNascimento = new javax.swing.JFormattedTextField();
        TBCEP = new javax.swing.JFormattedTextField();
        TBNumero = new javax.swing.JFormattedTextField();
        CBEstadoCivil = new javax.swing.JComboBox<>();
        CBCidade = new javax.swing.JComboBox<>();
        CBEstado = new javax.swing.JComboBox<>();
        TBNome = new javax.swing.JTextField();
        TBEmail = new javax.swing.JTextField();
        TBRua = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Psicólogos");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jScrollPane2.setPreferredSize(new java.awt.Dimension(1376, 783));

        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });

        jLabel1.setText("* CPF");

        jLabel2.setText("* Psicólogo");

        jLabel3.setText("E-mail");

        jLabel4.setText("Telefone");

        jLabel6.setText("Estado Civil");

        jLabel7.setText("Data de Nascimento");

        jLabel8.setText("Rua");

        jLabel9.setText("  Número");

        jLabel10.setText("Bairro");

        TBBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TBBairroActionPerformed(evt);
            }
        });

        jLabel12.setText("Cidade");

        jLabel13.setText("UF");

        jLabel11.setText("CEP");

        BCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Cadastrar.png"))); // NOI18N
        BCadastrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BCadastrarMouseClicked(evt);
            }
        });
        BCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCadastrarActionPerformed(evt);
            }
        });

        TABPsicologos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "CPF", "Nome", "Email", "Telefone", "Sexo", "Estado Civil", "Data Nascimento", "NºResidência", "CEP", "Rua", "Bairro", "Cidade", "UF"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TABPsicologos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TABPsicologosMouseClicked(evt);
            }
        });
        TABPsicologos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TABPsicologosKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(TABPsicologos);

        BAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Alterar.png"))); // NOI18N
        BAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAlterarActionPerformed(evt);
            }
        });

        BExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Excluir.png"))); // NOI18N
        BExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BExcluirActionPerformed(evt);
            }
        });

        BBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Pesquisar2.png"))); // NOI18N
        BBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BBuscarActionPerformed(evt);
            }
        });

        CBSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Masculino", "Feminino" }));

        jLabel5.setText("Sexo");

        try {
            TBCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            TBTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            TBDataNascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        TBDataNascimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TBDataNascimentoActionPerformed(evt);
            }
        });

        try {
            TBCEP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        TBNumero.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat(""))));
        TBNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TBNumeroActionPerformed(evt);
            }
        });

        CBEstadoCivil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Solteiro", "Casado", "Viúvo", "Divorciado" }));

        CBCidade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "São Paulo ", "Rio de Janeiro ", "Salvador ", "Brasília ", "Fortaleza ", "Belo Horizonte ", "Manaus ", "Curitiba ", "Recife ", "Porto Alegre ", "Belém ", "Goiânia ", "Guarulhos ", "Campinas ", "São Luís ", "São Gonçalo ", "Maceió ", "Duque de Caxias ", "Natal ", "Campo Grande ", "Teresina ", "São Bernardo do Campo ", "Nova Iguaçu ", "João Pessoa ", "Santo André ", "Osasco ", "São José dos Campos ", "Jaboatão dos Guararapes ", "Ribeirão Preto ", "Uberlândia ", "Contagem ", "Sorocaba ", "Aracaju ", "Feira de Santana ", "Cuiabá ", "Joinville ", "Juiz de Fora ", "Londrina ", "Aparecida de Goiânia ", "Ananindeua ", "Niterói ", "Porto Velho ", "Campos dos Goytacazes ", "Belford Roxo ", "Serra ", "Caxias do Sul ", "Vila Velha ", "Florianópolis ", "São João de Meriti ", "Mauá ", "Macapá ", "São José do Rio Preto ", "Santos ", "Mogi das Cruzes ", "Betim ", "Diadema ", "Campina Grande ", "Jundiaí ", "Maringá ", "Montes Claros ", "Carapicuíba ", "Olinda ", "Piracicaba ", "Cariacica ", "Bauru ", "Rio Branco ", "Anápolis ", "São Vicente ", "Vitória ", "Caucaia ", "Itaquaquecetuba ", "Caruaru ", "Pelotas ", "Vitória da Conquista ", "Canoas ", "Franca ", "Ponta Grossa ", "Blumenau ", "Petrolina ", "Paulista ", "Ribeirão das Neves ", "Uberaba ", "Boa Vista ", "Cascavel ", "Guarujá ", "Taubaté ", "Petrópolis ", "Limeira ", "Praia Grande ", "São José dos Pinhais ", "Santarém ", "Mossoró ", "Suzano ", "Camaçari ", "Governador Valadares ", "Santa Maria ", "Gravataí ", "Taboão da Serra ", "Várzea Grande ", "Palmas ", "Cidade ", "Juazeiro do Norte ", "Foz do Iguaçu ", "Sumaré ", "Volta Redonda ", "Barueri ", "Embu das Artes ", "Marabá ", "Ipatinga ", "Imperatriz ", "Viamão ", "Novo Hamburgo ", "São Carlos ", "Parnamirim ", "Magé ", "Marília ", "Sete Lagoas ", "Colombo ", "Macaé ", "Arapiraca ", "Divinópolis ", "São José ", "Itaboraí ", "São Leopoldo ", "Americana ", "Indaiatuba ", "Cotia ", "Jacareí ", "Araraquara ", "Presidente Prudente ", "Itapevi ", "Maracanaú ", "Itabuna ", "Juazeiro ", "Santa Luzia ", "Hortolândia ", "Rondonópolis ", "Dourados ", "Rio Grande ", "Cachoeiro de Itapemirim ", "Alvorada ", "Criciúma ", "Cabo Frio ", "Rio Verde ", "Chapecó ", "Itajaí ", "Sobral ", "Rio Claro ", "Cabo de Santo Agostinho ", "Passo Fundo ", "Araçatuba ", "Luziânia ", "Santa Bárbara d’Oeste ", "Lauro de Freitas ", "Castanhal ", "Angra dos Reis ", "Nova Friburgo ", "Parauapebas ", "Ferraz de Vasconcelos ", "Águas Lindas de Goiás ", "Ilhéus ", "Barra Mansa ", "Guarapuava ", "Nossa Senhora do Socorro ", "São José de Ribamar ", "Ibirité ", "Teresópolis ", "Mesquita ", "Araguaína ", "Francisco Morato ", "Itu ", "Itapecerica da Serra ", "Timon ", "Poços de Caldas ", "Jequié ", "Linhares ", "Caxias ", "Jaraguá do Sul ", "Pindamonhangaba ", "Bragança Paulista ", "Lages ", "Nilópolis ", "São Caetano do Sul ", "Teixeira de Freitas ", "Itapetininga ", "Palhoça ", "Alagoinhas ", "Camaragibe ", "Barreiras ", "Valparaíso de Goiás ", "Paranaguá ", "Parnaíba ", "Abaetetuba ", "Patos de Minas ", "Mogi Guaçu ", "Franco da Rocha ", "Porto Seguro ", "Maricá ", "Queimados ", "Pouso Alegre ", "Jaú ", " " }));

        CBEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "...", "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO", " " }));

        jLabel14.setText("Busca por Nome");

        jLabel15.setText("Campos Obrigatórios *");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(481, 481, 481)
                        .addComponent(jLabel15))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(BCadastrar)
                                        .addGap(14, 14, 14))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel1))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CBSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TBNome, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TBCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TBEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TBDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(TBTelefone, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(CBEstadoCivil, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(248, 248, 248)
                                .addComponent(BAlterar)
                                .addGap(64, 64, 64)
                                .addComponent(BExcluir)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(67, 67, 67)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel11)
                                                    .addComponent(jLabel12)
                                                    .addComponent(jLabel10)))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                        .addComponent(jLabel9)
                                                        .addGap(6, 6, 6)))))
                                        .addGap(18, 18, 18))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(16, 16, 16)
                                        .addComponent(jLabel8)
                                        .addGap(36, 36, 36)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TBCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TBRua, javax.swing.GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE)
                                    .addComponent(TBBairro)
                                    .addComponent(TBNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(133, 133, 133)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(CBCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(CBEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(31, 31, 31))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel14)
                                            .addComponent(TBBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(53, 53, 53)))
                                .addComponent(BBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1346, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(251, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel15)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TBCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TBRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TBNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(TBNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TBEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(CBEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(TBTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TBDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CBSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(CBEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(TBBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel14))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BAlterar)
                                    .addComponent(BExcluir)
                                    .addComponent(BCadastrar)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TBBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(TBCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CBCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)))
                    .addComponent(BBuscar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );

        jScrollPane2.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1420, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 745, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setBounds(0, 0, 1336, 783);
    }// </editor-fold>//GEN-END:initComponents
 
    private void BCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCadastrarActionPerformed
        
          if(TBNumero.getText().isEmpty()){
            TBNumero.setText("0");
         
         
         }
        
        if(TBCPF.getText().isEmpty()||TBNome.getText().isEmpty()){
            
            JOptionPane.showMessageDialog(null,"Preencher todos os campos obrigatórios");
            
        }
        else{
        PsicologoDAO pdao = new PsicologoDAO();
        Psicologo p = new Psicologo();
        Consulta c = new Consulta();
        ConsultaDAO cdao= new ConsultaDAO();

        p.setCpf(TBCPF.getText());
        p.setNome(TBNome.getText());
        p.setEmail(TBEmail.getText());
        p.setTelefone(TBTelefone.getText());
        p.setSexo(CBSexo.getSelectedItem().toString());
        p.setEstado_civil(CBEstadoCivil.getSelectedItem().toString());
        p.setData_nascimento( TBDataNascimento.getText());
        p.setNumero_endereco(Integer.parseInt(TBNumero.getText()));
        p.setCep(TBCEP.getText());
        p.setRua(TBRua.getText());
        p.setEstado(CBEstado.getSelectedItem().toString());
        p.setBairro(TBBairro.getText());
        p.setCidade(CBCidade.getSelectedItem().toString());

        
        
        pdao.createPsicologo(p);
            TBCPF.setText("");
            TBNome.setText("");
            TBEmail.setText("");
            TBDataNascimento.setText("");
            TBTelefone.setText("");
            TBNumero.setText("");
            TBCEP.setText("");
            TBRua.setText("");
            TBBairro.setText("");
        
        
       readJTable();
                
  }
        
      
 
        
        
       
        
        
    }//GEN-LAST:event_BCadastrarActionPerformed

    private void TBBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TBBairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TBBairroActionPerformed

    private void TABPsicologosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TABPsicologosMouseClicked
    // setar_campos();        
     
     if (TABPsicologos.getSelectedRow() != -1) {
            TBCPF.setText(TABPsicologos.getValueAt(TABPsicologos.getSelectedRow(),0).toString());
            TBNome.setText(TABPsicologos.getValueAt(TABPsicologos.getSelectedRow(),1).toString());
            TBEmail.setText(TABPsicologos.getValueAt(TABPsicologos.getSelectedRow(),2).toString());
            TBTelefone.setText(TABPsicologos.getValueAt(TABPsicologos.getSelectedRow(),3).toString());
            CBSexo.setSelectedItem((TABPsicologos.getValueAt(TABPsicologos.getSelectedRow(),4).toString()));
            CBEstadoCivil.setSelectedItem(TABPsicologos.getValueAt(TABPsicologos.getSelectedRow(),5).toString());
            TBDataNascimento.setText(TABPsicologos.getValueAt(TABPsicologos.getSelectedRow(),6).toString());
            TBNumero.setText(TABPsicologos.getValueAt(TABPsicologos.getSelectedRow(),7).toString());
            TBCEP.setText(TABPsicologos.getValueAt(TABPsicologos.getSelectedRow(),8).toString());
            TBRua.setText(TABPsicologos.getValueAt(TABPsicologos.getSelectedRow(),9).toString());
            TBBairro.setText(TABPsicologos.getValueAt(TABPsicologos.getSelectedRow(),10).toString()); 
            CBCidade.setSelectedItem(TABPsicologos.getValueAt(TABPsicologos.getSelectedRow(),11).toString());
            CBEstado.setSelectedItem(TABPsicologos.getValueAt(TABPsicologos.getSelectedRow(),12).toString());
            BCadastrar.setEnabled(false);
            BAlterar.setEnabled(true);
            BExcluir.setEnabled(true); 
            
            }
      
    }//GEN-LAST:event_TABPsicologosMouseClicked

    private void TABPsicologosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TABPsicologosKeyReleased

       //  setar_campos(); 
        
 
      if (TABPsicologos.getSelectedRow() != -1) {
            TBCPF.setText(TABPsicologos.getValueAt(TABPsicologos.getSelectedRow(),0).toString());
            TBNome.setText(TABPsicologos.getValueAt(TABPsicologos.getSelectedRow(),1).toString());
            TBEmail.setText(TABPsicologos.getValueAt(TABPsicologos.getSelectedRow(),2).toString());
            TBTelefone.setText(TABPsicologos.getValueAt(TABPsicologos.getSelectedRow(),3).toString());
            CBSexo.setSelectedItem((TABPsicologos.getValueAt(TABPsicologos.getSelectedRow(),4).toString()));
            CBEstadoCivil.setSelectedItem(TABPsicologos.getValueAt(TABPsicologos.getSelectedRow(),5).toString());
            TBDataNascimento.setText(TABPsicologos.getValueAt(TABPsicologos.getSelectedRow(),6).toString());
            TBNumero.setText(TABPsicologos.getValueAt(TABPsicologos.getSelectedRow(),7).toString());
            TBCEP.setText(TABPsicologos.getValueAt(TABPsicologos.getSelectedRow(),8).toString());
            TBRua.setText(TABPsicologos.getValueAt(TABPsicologos.getSelectedRow(),9).toString());
            TBBairro.setText(TABPsicologos.getValueAt(TABPsicologos.getSelectedRow(),10).toString()); 
            CBCidade.setSelectedItem(TABPsicologos.getValueAt(TABPsicologos.getSelectedRow(),11).toString());
            CBEstado.setSelectedItem(TABPsicologos.getValueAt(TABPsicologos.getSelectedRow(),12).toString());
            BCadastrar.setEnabled(false);
            BAlterar.setEnabled(true);
            BExcluir.setEnabled(true); 
            }
      
    }//GEN-LAST:event_TABPsicologosKeyReleased

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
       readJTable();
    }//GEN-LAST:event_formWindowActivated

    private void BAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAlterarActionPerformed
        if (TABPsicologos.getSelectedRow() != - 1) {
       
 int confirma = JOptionPane.showConfirmDialog(null,"Confirma a alteração deste Psicólogo? ","Atenção",JOptionPane.YES_NO_OPTION);
        if (confirma== JOptionPane.YES_OPTION){
            if(TBNumero.getText().isEmpty()){
            TBNumero.setText("0");
         
         
         }
         
          if(TBCPF.getText().isEmpty()||TBNome.getText().isEmpty()){
            
            JOptionPane.showMessageDialog(null,"Preencher todos os campos obrigatórios");
            
        }  
         
          else{
 
          Psicologo p =new Psicologo();
          PsicologoDAO pdao = new PsicologoDAO();

        
                  
                  
        p.setNome(TBNome.getText());
        p.setEmail(TBEmail.getText());
        p.setTelefone(TBTelefone.getText());
        p.setSexo(CBSexo.getSelectedItem().toString());
        p.setEstado_civil(CBEstadoCivil.getSelectedItem().toString());
        p.setData_nascimento( TBDataNascimento.getText());
        p.setNumero_endereco(Integer.parseInt(TBNumero.getText()));
        p.setCep(TBCEP.getText());
        p.setRua(TBRua.getText());
        p.setEstado(CBEstado.getSelectedItem().toString());
        p.setBairro(TBBairro.getText());
        p.setCidade(CBCidade.getSelectedItem().toString());
        p.setCpf((String)TABPsicologos.getValueAt(TABPsicologos.getSelectedRow(), 0));
 
         pdao.update(p);
            TBCPF.setText("");
            TBNome.setText("");
            TBEmail.setText("");
            TBTelefone.setText("");
            TBDataNascimento.setText("");
            TBNumero.setText("");
            TBCEP.setText("");
            TBRua.setText("");
            TBBairro.setText("");
            readJTable();
  }
            

        }
        
        
        
        else{
        
        }
        }
         else {
            JOptionPane.showMessageDialog(null, "Selecione um Psicólogo para alterar");
        
        }
    }//GEN-LAST:event_BAlterarActionPerformed

    private void BExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BExcluirActionPerformed
        if (TABPsicologos.getSelectedRow() != -1) {
 int confirma = JOptionPane.showConfirmDialog(null,"Confirma a exclusão deste Psicólogo? ","Atenção",JOptionPane.YES_NO_OPTION);
        if (confirma== JOptionPane.YES_OPTION){
         Psicologo p = new Psicologo();
         PsicologoDAO pdao = new PsicologoDAO();

            p.setCpf((String) TABPsicologos.getValueAt(TABPsicologos.getSelectedRow(), 0));
            
            pdao.delete(p);
            TBCPF.setText("");
            TBNome.setText("");
            TBEmail.setText("");
            TBTelefone.setText("");
            TBDataNascimento.setText("");
            TBNumero.setText("");
            TBCEP.setText("");
            TBRua.setText("");
            TBBairro.setText("");
          

            readJTable();

        
      }
      else{
              
              }
        }
         else {
            JOptionPane.showMessageDialog(null, "Selecione um Psicólogo para excluir.");
        }
    }//GEN-LAST:event_BExcluirActionPerformed

    private void BBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BBuscarActionPerformed
        readJTableForDesc(TBBuscar.getText());
    }//GEN-LAST:event_BBuscarActionPerformed

    private void TBNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TBNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TBNumeroActionPerformed

    private void TBDataNascimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TBDataNascimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TBDataNascimentoActionPerformed

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
            
       
    }//GEN-LAST:event_jPanel1MouseClicked

    private void BCadastrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BCadastrarMouseClicked
            TBCPF.setText("");
            TBNome.setText("");
            TBEmail.setText("");
            TBDataNascimento.setText("");
            TBNumero.setText("");
            TBTelefone.setText(""); 
            TBCEP.setText("");
            TBRua.setText("");
            TBBairro.setText("");
            BCadastrar.setEnabled(true);
            BAlterar.setEnabled(false);
            BExcluir.setEnabled(false);
    }//GEN-LAST:event_BCadastrarMouseClicked

    
   
   
        
    
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroPsicologo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroPsicologo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroPsicologo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroPsicologo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroPsicologo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BAlterar;
    private javax.swing.JButton BBuscar;
    private javax.swing.JButton BCadastrar;
    private javax.swing.JButton BExcluir;
    private javax.swing.JComboBox<String> CBCidade;
    private javax.swing.JComboBox<String> CBEstado;
    private javax.swing.JComboBox<String> CBEstadoCivil;
    private javax.swing.JComboBox<String> CBSexo;
    private javax.swing.JTable TABPsicologos;
    private javax.swing.JTextField TBBairro;
    private javax.swing.JTextField TBBuscar;
    private javax.swing.JFormattedTextField TBCEP;
    private javax.swing.JFormattedTextField TBCPF;
    private javax.swing.JFormattedTextField TBDataNascimento;
    private javax.swing.JTextField TBEmail;
    private javax.swing.JTextField TBNome;
    private javax.swing.JFormattedTextField TBNumero;
    private javax.swing.JTextField TBRua;
    private javax.swing.JFormattedTextField TBTelefone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
