/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Control.ContasPagarDAO;
import Control.UsuarioDAO;
import Model.ContasPagar;
import Model.Usuario;
import java.awt.Color;
import java.awt.FlowLayout;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author MARCELO
 */
public class TelaCadastroUsuario extends javax.swing.JFrame {
   
    /**
     * Creates new form Usuario
     */
    public TelaCadastroUsuario() {
        initComponents();
      ImageIcon icon = new ImageIcon(getClass().getResource("/Imagens/Emblema_Psicologia.png"));
        setIconImage(icon.getImage());
      
     
       
        DefaultTableModel modelo = (DefaultTableModel) TABUsuarios.getModel();
        TABUsuarios.setRowSorter(new TableRowSorter(modelo));

        readJTable();
            BCadastrar.setEnabled(true);
            BAlterar.setEnabled(false);
            BExcluir.setEnabled(false);
    }
    public void readJTable(){
     DefaultTableModel modelo = (DefaultTableModel) TABUsuarios.getModel();
        modelo.setNumRows(0);
        UsuarioDAO udao = new UsuarioDAO();

        for (Usuario u : udao.read()) {

            modelo.addRow(new Object[]{
                u.getCpf(),
                u.getLogin(),
                u.getSenha(),
                u.getPerfil()
                
                    
           
            });
        }
        }
     public void readJTableForDesc(String desc) {
        
        DefaultTableModel modelo = (DefaultTableModel) TABUsuarios.getModel();
        modelo.setNumRows(0);
       
        UsuarioDAO udao = new  UsuarioDAO();

        for ( Usuario u : udao.readForDesc(desc)) {

            
          
          modelo.addRow(new Object[]{
                u.getCpf(),
                u.getLogin(),
                u.getSenha(),
                u.getPerfil()
             
            });

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TBLogin = new javax.swing.JTextField();
        TBSenha = new javax.swing.JTextField();
        BCadastrar = new javax.swing.JButton();
        TBCPF = new javax.swing.JFormattedTextField();
        BExcluir = new javax.swing.JButton();
        BBuscar = new javax.swing.JButton();
        BAlterar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        CBPerfil = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        TABUsuarios = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        TBBuscar = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Usuários");
        setResizable(false);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        jLabel1.setText(" * CPF");

        jLabel3.setText("* Login");

        jLabel4.setText("* Senha");

        BCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Cadastrar.png"))); // NOI18N
        BCadastrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BCadastrarMouseClicked(evt);
            }
        });
        BCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCadastrarActionPerformed(evt);
            }
        });

        try {
            TBCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        BExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Excluir.png"))); // NOI18N
        BExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BExcluirActionPerformed(evt);
            }
        });

        BBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Pesquisar2.png"))); // NOI18N
        BBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BBuscarActionPerformed(evt);
            }
        });

        BAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Alterar.png"))); // NOI18N
        BAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAlterarActionPerformed(evt);
            }
        });

        jLabel2.setText("Campos Obrigatórios *");

        CBPerfil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Psicólogo" }));

        TABUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "CPF", "Login", "Senha", "Perfil"
            }
        ));
        TABUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TABUsuariosMouseClicked(evt);
            }
        });
        TABUsuarios.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TABUsuariosKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(TABUsuarios);

        jLabel5.setText("Busca por Login");

        TBBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TBBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TBCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(115, 115, 115)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)))
                    .addComponent(CBPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TBLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TBSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addComponent(TBBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(BCadastrar)
                        .addGap(115, 115, 115)
                        .addComponent(BAlterar)
                        .addGap(121, 121, 121)
                        .addComponent(BExcluir))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(362, 362, 362)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(133, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(BCadastrar)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(BExcluir))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(TBCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(TBLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel4)
                                            .addComponent(TBSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(57, 57, 57)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(TBBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(CBPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel5)
                                        .addGap(96, 96, 96))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(BBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)))))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(BAlterar)))
                .addGap(16, 16, 16))
        );

        setBounds(0, 0, 996, 713);
    }// </editor-fold>//GEN-END:initComponents

    private void BCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCadastrarActionPerformed
 

           
        if(TBLogin.getText().isEmpty()||TBSenha.getText().isEmpty()){
               
               JOptionPane.showMessageDialog(null,"Preencha todos os campos obrigatórios"); 
              } 
              else{
                 Usuario u = new Usuario();
                 UsuarioDAO udao = new UsuarioDAO();
                
            u.setCpf(TBCPF.getText());
            u.setLogin(TBLogin.getText());
            u.setSenha(TBSenha.getText());
            u.setPerfil(CBPerfil.getSelectedItem().toString());
         
            
                udao.createUser(u);
                TBCPF.setText("");
                TBLogin.setText("");
                TBSenha.setText("");
                  readJTable();
                  
        
               
            
        }        
          
    }//GEN-LAST:event_BCadastrarActionPerformed

    private void BExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BExcluirActionPerformed
        if (TABUsuarios.getSelectedRow() != -1) {
         int confirma = JOptionPane.showConfirmDialog(null,"Confirma a exclusão deste Usuário? ","Atenção",JOptionPane.YES_NO_OPTION);
        if (confirma== JOptionPane.YES_OPTION){
       UsuarioDAO dao = new UsuarioDAO();
       Usuario u = new Usuario();
       
       u.setCpf((String) TABUsuarios.getValueAt(TABUsuarios.getSelectedRow(),0));
       dao.delete(u);
         TBCPF.setText("");
         TBLogin.setText("");
         TBSenha.setText("");
        readJTable();
        }
        else{
        
        
        }
        }
       else {
            JOptionPane.showMessageDialog(null, "Selecione um Usuário para excluir.");
        }
       
       
       
       
    }//GEN-LAST:event_BExcluirActionPerformed

    private void BAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAlterarActionPerformed
       if (TABUsuarios.getSelectedRow() != -1) {
  int confirma = JOptionPane.showConfirmDialog(null,"Confirma a alteração deste Usuário? ","Atenção",JOptionPane.YES_NO_OPTION);
        if (confirma== JOptionPane.YES_OPTION){
            
           if(TBCPF.getText().isEmpty()||TBLogin.getText().isEmpty()||TBSenha.getText().isEmpty()){
               
               JOptionPane.showMessageDialog(null,"Preencha todos os campos obrigatórios"); 
              } 
            
           else{
               
             Usuario u = new  Usuario();
             UsuarioDAO dao = new  UsuarioDAO();

            u.setLogin(TBLogin.getText());
            u.setSenha(TBSenha.getText());
            u.setPerfil(CBPerfil.getSelectedItem().toString());
           
            u.setCpf((String) TABUsuarios.getValueAt(TABUsuarios.getSelectedRow(), 0));
            
            dao.update(u);

            TBLogin.setText("");
            TBSenha.setText("");
            TBCPF.setText("");
           readJTable();
           }
           

        }
       
        else{
        
        }
       }
       else{
         JOptionPane.showMessageDialog(null, "Selecione um Usuário para alterar");
       }
    }//GEN-LAST:event_BAlterarActionPerformed

    private void BBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BBuscarActionPerformed
       readJTableForDesc(TBBuscar.getText());
    }//GEN-LAST:event_BBuscarActionPerformed

    private void TABUsuariosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TABUsuariosKeyReleased
      if (TABUsuarios.getSelectedRow() != -1) {
           TBCPF.setText(TABUsuarios.getValueAt(TABUsuarios.getSelectedRow(), 0).toString());
            TBLogin.setText(TABUsuarios.getValueAt(TABUsuarios.getSelectedRow(), 1).toString());
             TBSenha.setText(TABUsuarios.getValueAt(TABUsuarios.getSelectedRow(), 2).toString());
             CBPerfil.setSelectedItem(TABUsuarios.getValueAt(TABUsuarios.getSelectedRow(), 3).toString());
    
                    BCadastrar.setEnabled(false);
                    BAlterar.setEnabled(true);
                    BExcluir.setEnabled(true);

        } 
    }//GEN-LAST:event_TABUsuariosKeyReleased

    private void TABUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TABUsuariosMouseClicked
        if (TABUsuarios.getSelectedRow() != -1) {
           TBCPF.setText(TABUsuarios.getValueAt(TABUsuarios.getSelectedRow(), 0).toString());
            TBLogin.setText(TABUsuarios.getValueAt(TABUsuarios.getSelectedRow(), 1).toString());
             TBSenha.setText(TABUsuarios.getValueAt(TABUsuarios.getSelectedRow(), 2).toString());
             CBPerfil.setSelectedItem(TABUsuarios.getValueAt(TABUsuarios.getSelectedRow(), 3).toString());
    
                              BCadastrar.setEnabled(false);
                              BAlterar.setEnabled(true);
                              BExcluir.setEnabled(true);

        } 
    }//GEN-LAST:event_TABUsuariosMouseClicked

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
           
    }//GEN-LAST:event_formMouseClicked

    private void BCadastrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BCadastrarMouseClicked
            TBLogin.setText("");
            TBSenha.setText("");
            TBCPF.setText("");
            BCadastrar.setEnabled(true);
            BAlterar.setEnabled(false);
            BExcluir.setEnabled(false);    }//GEN-LAST:event_BCadastrarMouseClicked

    private void TBBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TBBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TBBuscarActionPerformed

  
    

    

   

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BAlterar;
    private javax.swing.JButton BBuscar;
    private javax.swing.JButton BCadastrar;
    private javax.swing.JButton BExcluir;
    public static javax.swing.JComboBox<String> CBPerfil;
    private javax.swing.JTable TABUsuarios;
    private javax.swing.JTextField TBBuscar;
    private javax.swing.JFormattedTextField TBCPF;
    private javax.swing.JTextField TBLogin;
    private javax.swing.JTextField TBSenha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables

    
}
